# Run the following command: snakemake --use-conda --cores 32 output/ecoli_10.vg

rule index_gen:
    output:
        "output/{dataset}_{seqcount}/{dataset}_{seqcount}.fa.gz"
    
    input:
        "dataset/{dataset}/{dataset}_{seqcount}.fa"

    conda:
        "envs/pggb.yaml"

    shell:
        '''
        bgzip -c {input} > {output}
        samtools faidx {output}
        '''

rule gfa:
    output:
        "output/{dataset}_{seqcount}.gfa"
    
    input:
        # "output/{dataset}_{seqcount}/",
        "output/{dataset}_{seqcount}/{dataset}_{seqcount}.fa.gz"
        
    
    conda:
        "envs/pggb.yaml"
    
    shell:
        '''
        pggb -i {input} -p 95 -s 30000 -G 2000 -n 2 -t 32 -v -o output/{wildcards.dataset}_{wildcards.seqcount}/ -M -m
        mv output/{wildcards.dataset}_{wildcards.seqcount}/*.gfa {output}
        rm -rf output/{wildcards.dataset}_{wildcards.seqcount}/
	'''


rule vg_install:
    output:
        "vg/vg"
    
    shell:
        '''
        cd vg/
        wget https://github.com/vgteam/vg/releases/download/v1.42.0/vg
        chmod +x vg
        cd ../
        '''


rule vg:
    output:
        "output/{dataset}_{seqcount}.vg"
    
    input:
        "vg/vg",
        "output/{dataset}_{seqcount}.gfa"
    
    conda:
        "envs/pggb.yaml"
    
    shell:
        '''
	./vg/vg convert -p {input[1]} -v > {output}
        '''

rule pangraph:
    output:
        "output/{dataset}_{seqcount}.json"

    input:
        "output/{dataset}_{seqcount}.fa"

    shell:
        '''
        wget https://github.com/neherlab/pangraph/archive/refs/tags/0.6.2.zip
        unzip 0.6.2.zip
        cd pangraph-0.6.2/
        export jc="$PWD/pangraph/bin/julia" make pangraph && make install
        cd ../
        ./pangraph-0.6.2/pangraph/bin/pangraph build {input[0]} > {output}
        '''

rule mat:
    output:
        "output/{dataset}_{seqcount}.mat"

    input:
        "output/{dataset}_{seqcount}.json"
        "output/{dataset}_{seqcount}.nwk"
    
    shell:
        '''
        python3 mat_gen.py {input[0]} {input[1]} {output}
        '''