# Run the following command: snakemake --cores 32 output/ecoli_50.cram
rule sam:
    output:
        "output/{dataset}_{seqcount}.sam"
    input:
        "dataset/{dataset}_{seqcount}_r.fa",
        "dataset/{dataset}_{seqcount}_n-1.fa",
    threads: 8
    conda:
        "envs/samtools.yaml"
    shell:
        "minimap2 -a -t {threads} {input} > {output}"

rule bam:
    output:
        "output/{dataset}_{seqcount}.bam"
    input:
        "output/{dataset}_{seqcount}.sam"
    threads: 8
    conda:
        "envs/samtools.yaml"
    shell:
        "samtools view -@ {threads} -S -b  {input} > {output}"


rule cram:
    output:
        "output/{dataset}_{seqcount}.cram"
    input:
        "dataset/{dataset}_{seqcount}_r.fa",
        "output/{dataset}_{seqcount}.bam"
    threads: 8
    conda:
        "envs/samtools.yaml"
    shell:
        "samtools view -@ {threads}-C -T  {input} > {output}"

