# Run the following command: snakemake --use-conda --cores 32 -n output/ecoli_50.cram
rule sam:
    output:
        "output/{dataset}_{seqcount}.sam"
    input:
        "output/{dataset}_{seqcount}_r.fa",
        "output/{dataset}_{seqcount}_n-1.fa",
    threads: 8
    conda:
        "envs/samtools.yaml"
    shell:
        "minimap2 -a -t {threads} {input} > {output}"

rule bam:
    output:
        "output/{dataset}_{seqcount}.bam"
    input:
        "output/{dataset}_{seqcount}.sam"
    threads: 8
    conda:
        "envs/samtools.yaml"
    shell:
        "samtools view -S -b -t {threads} {input} > {output}"


rule cram:
    output:
        "output/{dataset}_{seqcount}.cram"
    input:
        "output/{dataset}_{seqcount}_r.fa",
        "output/{dataset}_{seqcount}.bam"
    threads: 8
    conda:
        "envs/samtools.yaml"
    shell:
        "samtools view -C -T -t {threads} {input} > {output}"
