'''
This is a snakemake workflow for building PanMAN from alignments (PanGraph, GFA, or MSA) or fragmented assembly.

Users can run workflow as:

Building PanMAN from PanGraph Alignment
    snakemake --use-conda --cores [num threads] --config RUNTYPE="pangraph" FASTA="[user_fa]" SEQ_COUNT=[haplotype_count] ASSEM="None" REF="None" TARGET="None"
Building PanMAN from PGGB Alignment
    snakemake --use-conda --cores [num threads] --config RUNTYPE="gfa" FASTA="[user_fa]" SEQ_COUNT=[haplotype_count] ASSEM="None" REF="None" TARGET="None"
Building PanMAN from MAFFT Alignment
    snakemake --use-conda --cores [num threads] --config RUNTYPE="msa" FASTA="[user_fa]" SEQ_COUNT=[haplotype_count] ASSEM="None" REF="None" TARGET="None"

Building PanMAN from Fragmented Assembly
    snakemake --use-conda --cores [num threads] --config RUNTYPE="pangraph/gfa/msa" FASTA="None" SEQ_COUNT=[haplotype_count] ASSEM="frag" REF="[user_fa]" TARGET="[target.txt]" 

Note: This workflow uses MashTree to build tree input for panmanUtils when building panman from GFA or MSA.
'''

def assem_rule(config):
    assembly_rule = config.get("ASSEM", None)
    if assembly_rule == "frag":
        return "output/input_concat.fa"
    else:
        return None

def config_select(config):
    target_rule = config.get("RUNTYPE", None)
    assembly_rule = config.get("ASSEM", None)
    
    if assembly_rule == "frag":
        if target_rule == "pangraph":
            return "output/frag_pangraph.aln"
        elif target_rule == "gfa":
            return "output/frag_pggb.aln"
        elif target_rule == "msa":
            return "output/frag_mafft.aln"    
        else:
            raise ValueError(f"Unknown target rule '{target_rule}'. Choose from 'pangraph', 'gfa', or 'msa'.")
    else:
        if target_rule == "pangraph":
            return "output/pangraph.aln"
        elif target_rule == "gfa":
            return "output/pggb.aln"
        elif target_rule == "msa":
            return "output/mafft.aln"    
        else:
            raise ValueError(f"Unknown target rule '{target_rule}'. Choose from 'pangraph', 'gfa', or 'msa'.")


rule all:
    input:
        assem_rule(config) or [],
        config_select(config)

rule wfmash:
    input:
        ref = config["REF"],
        target = config["TARGET"]
    output:
        concat_file = "output/input_concat.fa"
    threads:
        threads = 32
    shell:
        '''
        mkdir -p output/concat
        scripts/wfmash.sh {input.ref} {input.target} output/concat
        cat output/concat/* > {output.concat_file}
        cat {input.ref} >> {output.concat_file}
	'''

rule pangraph_frag:
    input:
        "output/input_concat.fa"
    output:
        aln = "output/frag_pangraph.aln",
        newick = "output/pangraph.nwk",
        panman = "panman/out.panman"
    threads:
        threads = 32
    shell:
        '''
        echo "Building Alignment with PanGraph..."
        export JULIA_NUM_THREADS={threads}
        mkdir -p output
        pangraph build {input[0]} > {output.aln} 2> {output.newick}
        awk '/tree/ {{split($0,a,"tree:  "); print a[2]}}' {output.newick} > temp.newick && mv temp.newick {output.newick}

        echo "Building PanMAN from Pangraph alignment..."
        ../build/panmanUtils -P {output.aln} -N {output.newick} -o out
        '''

rule pangraph:
    input:
        config["FASTA"]
    output:
        aln = "output/pangraph.aln",
        newick = "output/pangraph.nwk",
        panman = "panman/out.panman"
    threads:
        threads = 32
    shell:
        '''
        echo "Building Alignment with PanGraph..."
        export JULIA_NUM_THREADS={threads}
        mkdir -p output
        pangraph build {input[0]} > {output.aln} 2> {output.newick}
        awk '/tree/ {{split($0,a,"tree:  "); print a[2]}}' {output.newick} > temp.newick && mv temp.newick {output.newick}

        echo "Building PanMAN from Pangraph alignment..."
        ../build/panmanUtils -P {output.aln} -N {output.newick} -o out
        '''

rule mashtree_frag:
    input:
        "output/input_concat.fa"
    output:
        newick = "output/mashtree.nwk"
    threads:
        threads = 32
    shell:
        '''
        echo "Building Tree with MashTree..."
        mkdir -p output
        python3 scripts/splitSeqs.py {input[0]} temp
        mashtree --numcpus {threads} temp/* > {output.newick}
        python3 scripts/updateNewick.py {output.newick} temp_dir {output.newick}
        rm -r temp temp_dir
        '''

rule mashtree:
    input:
        config["FASTA"]
    output:
        newick = "output/mashtree.nwk"
    threads:
        threads = 32
    shell:
        '''
        echo "Building Tree with MashTree..."
        mkdir -p output
        python3 scripts/splitSeqs.py {input[0]} temp
        mashtree --numcpus {threads} temp/* > {output.newick}
        python3 scripts/updateNewick.py {output.newick} temp_dir {output.newick}
        rm -r temp temp_dir
        '''

rule mafft_frag:
    input:
        fasta = "output/input_concat.fa",
        newick = "output/mashtree.nwk"
    output:
        aln = "output/frag_mafft.aln",
        panman = "panman/out.panman"
    threads:
        threads = 32
    shell:
        '''
        echo "Building Alignment with MAFFT..."
        mafft --auto {input.fasta} > {output.aln}

        echo "Building PanMAN from MAFFT alignment..."
        ../build/panmanUtils -M {output.aln} -N {input.newick} -o out
        '''

rule mafft:
    input:
        fasta = config["FASTA"],
        newick = "output/mashtree.nwk"
    output:
        aln = "output/mafft.aln",
        panman = "panman/out.panman"
    threads:
        threads = 32
    shell:
        '''
        echo "Building Alignment with MAFFT..."
        mafft --auto {input.fasta} > {output.aln}

        echo "Building PanMAN from MAFFT alignment..."
        ../build/panmanUtils -M {output.aln} -N {input.newick} -o out
        '''

rule pggb_frag:
    input:
        fasta = "output/input_concat.fa",
        newick = "output/mashtree.nwk"
    output:
        aln = "output/frag_pggb.aln",
        panman = "panman/out.panman"
    threads:
        threads = 32
    params:
        sq = config["SEQ_COUNT"]
    shell:
        '''
        echo "Building Alignment with PGGB..."
        samtools faidx {input.fasta}
        pggb --threads {threads} -i {input.fasta} -o pggb_temp -n {params.sq}
        mv pggb_temp/*final.gfa {output.aln}
        rm -r pggb_temp

        echo "Building PanMAN from PGGB alignment..."
        ../build/panmanUtils -G {output.aln} -N {input.newick} -o out
        '''

rule pggb:
    input:
        fasta = config["FASTA"],
        newick = "output/mashtree.nwk"
    output:
        aln = "output/pggb.aln",
        panman = "panman/out.panman"
    threads:
        threads = 32
    params:
        sq = config["SEQ_COUNT"]
    shell:
        '''
        echo "Building Alignment with PGGB..."
        samtools faidx {input.fasta}
        pggb --threads {threads} -i {input.fasta} -o pggb_temp -n {params.sq}
        mv pggb_temp/*final.gfa {output.aln}
        rm -r pggb_temp

        echo "Building PanMAN from PGGB alignment..."
        ../build/panmanUtils -G {output.aln} -N {input.newick} -o out
        '''

